### ISSUE TITLE
All Wireframes

### ISSUE THREAD

**Issue by aaronqwerty** [muulinha/Project1#33]
- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Settings

**Comment by Pia-Fierro** [comment]
Initial look of page one done.

**Comment by Pia-Fierro** [comment]
Wireframe changed.
working in the application of new look for website.

**Comment by Pia-Fierro** [comment]
pages 1 and 1 styled. 
If there is more time available there is room for improvements.

**Comment by Pia-Fierro** [comment]
3erd page done. 
Working on modal look.
